### ISSUE TITLE
Make image_dir and job_dir central configurations in config file.

### ISSUE THREAD

**Issue by clennan** [idealo/imageatm#18]
- currently `image_dir` and `job_dir` can be set in config file for each component
- better to make them central configurations, i.e. put them on the same level as components in config file
- should be more user friendly, as we avoid complicated overwriting of `image_dir` and `job_dir` based on which components run first etc.

old format:
```
data_prep:
  run: True
  samples_file: sample_configfile.json
  image_dir: sample_dataset/
  job_dir: sample_jobdir/
  resize: True

train:
  run: True
  cloud: False

evaluate:
  run: True

cloud:
  cloud_tag: image_atm_example_tag
  provider: aws
  tf_dir: cloud/aws
  region: eu-west-1
  vpc_id: vpc-example
  instance_type: p2.xlarge
  bucket: s3://example-bucket
  destroy: True
```

new format:
```
image_dir: sample_dataset/
job_dir: sample_jobdir/

data_prep:
  run: True
  samples_file: sample_configfile.json
  resize: True

train:
  run: True
  cloud: False

evaluate:
  run: True

cloud:
  cloud_tag: image_atm_example_tag
  provider: aws
  tf_dir: cloud/aws
  region: eu-west-1
  vpc_id: vpc-example
  instance_type: p2.xlarge
  bucket: s3://example-bucket
  destroy: True
```
