### ISSUE TITLE
Evaluation report as jupyter notebook fails in cell 7

### ISSUE THREAD

**Issue by drosin** [idealo/imageatm#36]
The following error appears when generating the evaluation report as jupyter notebook:
```
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [7]":
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-a62122680ff8> in <module>
----> 1 e._plot_classification_report(figsize=[max(5,e.n_classes*0.5), max(8,e.n_classes*0.8)])

AttributeError: 'Evaluation' object has no attribute '_plot_classification_report'
```
This is my config.yml:
```
evaluate:
  run: True
  report:
    create: True
    kernel_name: imageatm
    export_html: True
    export_pdf: False
```
